name: dart_practice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  equatable: ^2.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  lints: ^6.0.0
  test: ^1.25.6
